functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: src/atlas-service-broker
  "go_unit_tests":
    - command: shell.exec
      type: system
      params:
        working_dir: src/atlas-service-broker
        script: |
          go test -v ./pkg/... > unit_result.suite
  "go_unit_tests_parse":
    - command: gotest.parse_files
      params:
        files: ["src/atlas-service-broker/unit_result.suite"]
  "go_vet":
    - command: shell.exec
      type: system
      params:
        working_dir: src/atlas-service-broker
        script: |
          go vet ./...
  "integration_tests":
    - command: shell.exec
      params:
        working_dir: src/atlas-service-broker
        script: |
          export ATLAS_BASE_URL=${atlas_base_url}
          export ATLAS_GROUP_ID=${atlas_group_id}
          export ATLAS_PUBLIC_KEY=${atlas_public_key}
          export ATLAS_PRIVATE_KEY=${atlas_private_key}
          go test -v ./test > int_result.suite
  "integration_tests_parse":
    - command: gotest.parse_files
      params:
        files: ["src/atlas-service-broker/int_result.suite"]

tasks:
  - name: unit_tests
    commands:
      - func: "go_unit_tests"
      - func: "go_unit_tests_parse"
  - name: vet
    commands:
      - func: "go_vet"
  - name: integration_tests
    commands:
      - func: "integration_tests"
      - func: "integration_tests_parse"

task_groups:
  - name: unit_task_group
    setup_group:
      - func: "fetch_source"
    tasks:
      - unit_tests
      - vet
  - name: integration_task_group
    setup_group:
      - func: "fetch_source"
    tasks:
      - integration_tests

buildvariants:
  - name: archlinux
    run_on: archlinux-test
    tasks:
      - unit_task_group
      - integration_task_group
