functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: src/atlas-service-broker
  "go_unit_tests":
    - command: shell.exec
      type: system
      params:
        working_dir: src/atlas-service-broker
        script: |
          go test -v ./pkg/... | tee unit_result.suite
    - command: gotest.parse_files
      params:
        files: ["src/atlas-service-broker/unit_result.suite"]
  "go_vet":
    - command: shell.exec
      type: system
      params:
        working_dir: src/atlas-service-broker
        script: |
          go vet ./...
  "integration_tests":
    - command: shell.exec
      params:
        working_dir: src/atlas-service-broker
        script: |
          export ATLAS_BASE_URL=${atlas_base_url}
          export ATLAS_GROUP_ID=${atlas_group_id}
          export ATLAS_PUBLIC_KEY=${atlas_public_key}
          export ATLAS_PRIVATE_KEY=${atlas_private_key}
          go test -timeout 1h -v ./test | tee int_result.suite
    - command: gotest.parse_files
      params:
        files: ["src/atlas-service-broker/int_result.suite"]
  "get_tagged_version":
    - command: shell.exec
      params:
        working_dir: src/atlas-service-broker
        script: |
          # Get version from tag on head and throw error if none exists
          export VERSION=$(git tag -l --points-at HEAD | sed 's/^v\(.*\)/\1/')
          [[ -z "$VERSION" ]] && { echo "No version tag on HEAD" ; exit 1; }

          echo "version: \"$VERSION\"" > version_expansion.yaml
    - command: expansions.update
      params:
        ignore_missing_file: true
        file: src/atlas-service-broker/version_expansion.yaml
  "build_binaries":
    - command: shell.exec
      params:
        working_dir: src/atlas-service-broker
        script: |
          ./scripts/build-production-binary.sh artifacts/atlas-service-broker-linux-arm64-${version}
  "setup_hub":
    - command: shell.exec
      params:
        script: |
          sudo pacman  --refresh --noconfirm -S hub
          echo "Installed Hub CLI"
  "publish_github_release":
    - command: shell.exec
      params:
        working_dir: src/atlas-service-broker
        script: |
          export GITHUB_TOKEN=8af0123063041586b4b9c501a4ad00190c56d192

          # Get all artifacts and turn them into a list with --attach flags
          export ARTIFACTS_ATTACH=$(ls artifacts | xargs -I {} echo "--attach artifacts/{} ")

          hub release create --message "Atlas Service Broker ${version}" $ARTIFACTS_ATTACH v${version}
  "setup_docker":
    - command: shell.exec
      params:
        script: |
          sudo pacman --refresh --noconfirm -S community/docker
          systemctl start docker.service
  "build_docker":
    - command: shell.exec
      params:
        working_dir: src/atlas-service-broker
        script: |
          docker build . -t ${docker_repo}/${docker_name}:${version} # by default
          docker build . -t ${docker_repo}/${docker_name}:$([[ ${version} =~ [0-9]+.[0-9]+$ ]] && echo "latest" || echo ${version})
  "publish_docker":
    - command: shell.exec
      params:
        working_dir: src/atlas-service-broker
        script: |
          docker login --username ${docker_username} --password ${docker_password} ${docker_repo}

          docker push ${docker_repo}/${docker_name}:${version} # by default
          docker push ${docker_repo}/${docker_name}:$([[ ${version} =~ [0-9]+.[0-9]+$ ]] && echo "latest" || echo ${version})

tasks:
  - name: unit_tests
    commands:
      - func: "go_unit_tests"
  - name: vet
    commands:
      - func: "go_vet"
  - name: integration_tests
    commands:
      - func: "integration_tests"
  - name: release_github
    patch_only: true
    commands:
      - func: "fetch_source"
      - func: "get_tagged_version"
      - func: "build_binaries"
      - func: "setup_hub"
      - func: "publish_github_release"
  - name: release_docker
    patch_only: true
    depends_on:
      - name: release_github
    commands:
      - func: "fetch_source"
      - func: "get_tagged_version"
      - func: "setup_docker"
      - func: "build_docker"
      - func: "publish_docker"

task_groups:
  - name: unit_task_group
    setup_group:
      - func: "fetch_source"
    tasks:
      - unit_tests
      - vet
  - name: integration_task_group
    setup_group:
      - func: "fetch_source"
    tasks:
      - integration_tests

buildvariants:
  - name: test
    run_on: archlinux-test
    tasks:
      - unit_task_group
      - integration_task_group
  - name: release
    run_on: archlinux-test
    tasks:
      - release_github
      - release_docker

