functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: src/atlas-service-broker
  "go_unit_tests":
    - command: shell.exec
      type: system
      params:
        working_dir: src/atlas-service-broker
        script: |
          go test -v ./... > result.suite
  "go_unit_tests_parse":
    - command: gotest.parse_files
      params:
        files: ["src/atlas-service-broker/*.suite"]
  "go_vet":
    - command: shell.exec
      type: system
      params:
        working_dir: src/atlas-service-broker
        script: |
          go vet ./...


tasks:
  - name: unit_tests
    commands:
      - func: "go_unit_tests"
      - func: "go_unit_tests_parse"
  - name: vet
    commands:
      - func: "go_vet"

task_groups:
  - name: unit_task_group
    setup_group:
      - func: "fetch_source"
    tasks:
      - unit_tests
      - vet

buildvariants:
  - name: archlinux
    run_on: archlinux-test
    tasks:
      - unit_task_group
