apiVersion: v1
kind: Service
metadata:
  name: atlas-service-broker
  labels:
    app: atlas-service-broker
spec:
  selector:
    app: atlas-service-broker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
